### ISSUE TITLE
GA4, Clarity 연결

### ISSUE THREAD

**Issue by Leejha** [career-sponsor/career.sponsor#5]
### background
* 데이터를 중심으로 빠른 실험
* google tag manager을 통해, 다양한 직군의 사람이 ga와 clarity를 설정할 수 있도록 구현

### action
* [x] google tag manager 연결
* [x] ga 도입
* [x] clarity 도입

**Comment by bgpark82** [comment]
GA4: https://analytics.google.com/analytics/web/#/p450437893/reports/intelligenthome?params=_u..nav%3Dmaui
GTM: https://tagmanager.google.com/#/container/accounts/6241774956/containers/190935543/workspaces/3
Clarity: https://clarity.microsoft.com/projects/view/n8qzjndjfk/dashboard?date=Last%203%20days
